### ISSUE TITLE
Testing bst proxy lambda with state handlers

### ISSUE THREAD

**Issue by nedosa** [bespoken/bst#208] opened 2017-03-02 09:10 UTC
I'm trying to test a new skill that makes heavy use of states with the `bst proxy lambda` tool (very nice btw) but it seems that `this.handler.state` is not been saved.

Is that right ? Is there any way to simulate saving state ?

**Comment by jkelvie** [comment] 2017-03-02 15:56
Hi @nedosa - you are referring to the handler.state that is part of the Node.js SDK for Alexa, correct?

This property in particular, I believe:
https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/blob/master/lib/alexa.js#L230

Are you working with one of the Alexa sample projects? In general, the Alexa SDK saves state to dynamo, though there are a few gotches and tricks to it. If you can share your project with me, or what your project is based on, I can probably help you sort it out.

**Comment by nedosa** [comment] 2017-03-02 17:17
Great, I'll get this working and paste the results here.

**Comment by nedosa** [comment] 2017-03-02 18:40
This is a very simple interaction (identifiers removed)
```
INFO  2017-03-02T18:39:12.693Z RequestReceived: POST /?node-id= ID: 
VERB  2017-03-02T18:39:12.694Z Payload:
{
  "version": "1.0",
  "session": {
    "new": true,
    "sessionId": "",
    "application": {
      "applicationId": ""
    },
    "attributes": {},
    "user": {
      "userId": ""
    }
  },
  "request": {
    "type": "LaunchRequest",
    "requestId": "",
    "timestamp": "2017-03-02T18:37:20Z",
    "locale": "en-US"
  }
}
INFO  2017-03-02T18:39:12.695Z Forwarding localhost:10000
Warning: Application ID is not set
INIT.Welcome state: _INIT
INFO  2017-03-02T18:39:12.982Z ResponseReceived ID: 
VERB  2017-03-02T18:39:12.983Z Payload:
{
  "version": "1.0",
  "response": {
    "outputSpeech": {
      "type": "SSML",
      "ssml": "<speak>  </speak>"
    },
    "shouldEndSession": true
  },
  "sessionAttributes": {
    "STATE": "_INIT"
  }
}



INFO  2017-03-02T18:39:45.352Z RequestReceived: POST /?node-id= ID: 
VERB  2017-03-02T18:39:45.352Z Payload:
{
  "version": "1.0",
  "session": {
    "new": true,
    "sessionId": "",
    "application": {
      "applicationId": ""
    },
    "attributes": {},
    "user": {
      "userId": ""
    }
  },
  "request": {
    "type": "IntentRequest",
    "requestId": "",
    "timestamp": "2017-03-02T18:37:52Z",
    "locale": "en-US",
    "intent": {
      "name": "AMAZON.YesIntent"
    },
    "inDialog": false
  }
}
INFO  2017-03-02T18:39:45.353Z Forwarding localhost:10000
Warning: Application ID is not set
newSessionHandlers.Unhandled [object Object]
newSessionHandlers.Unhandled
INFO  2017-03-02T18:39:45.361Z ResponseReceived ID: 1488479840045
VERB  2017-03-02T18:39:45.362Z Payload:
{
  "version": "1.0",
  "response": {
    "outputSpeech": {
      "type": "SSML",
      "ssml": "<speak> </speak>"
    },
    "shouldEndSession": false,
    "reprompt": {
      "outputSpeech": {
        "type": "SSML",
        "ssml": "<speak></speak>"
      }
    }
  },
  "sessionAttributes": {}
}

```

**Comment by nedosa** [comment] 2017-03-02 18:41
I wonder if it is the `"shouldEndSession": true` that is causing the lost state. Why would the SDK advise for ending the session, any ideas ?

**Comment by jkelvie** [comment] 2017-03-02 18:59
The shouleEndSession flag is the cause. If you look at the second request, you will see that it says session.new = true. That is a result of closing the session in the first response. If you instead say shouldEndSession = false, the attributes will then come back to you, and should be made available via the SDK.

I'm not sure where it advises to end the session, but in general, the idea is you should end it when the interaction with the user is done. As long as you are prompting the user to say something, you should keep the session open.

**Comment by nedosa** [comment] 2017-03-02 19:06
Thanks @jkelvie . Oddly, when my code redirects to the `Welcome` method, I'm only emitting a `:tell` response, like the following:
```
    "Welcome": function () {
        console.log('INIT.Welcome state: ' + this.handler.state);
        this.emit(":tell", instructions["WELCOME"]);
    },
```
but it seems that the Alexa SDK set the `shouldEndSession` flag to `true` in `response.js`:
```
        ':tell': function (speechOutput) {
            if(this.isOverridden()) {
                return;
            }

            this.handler.response = buildSpeechletResponse({
                sessionAttributes: this.attributes,
                output: getSSMLResponse(speechOutput),
                shouldEndSession: true
            });
            this.emit(':responseReady');
        },
```

I wonder if this is a bug or intented behaviour.

**Comment by jkelvie** [comment] 2017-03-02 19:28
That is intended behavior. The idea is that "tell" does not expect a response from the user, so the session should be closed. The "ask" and "askWithCard" routines are the ones that will keep the session open, because they prompt the user for a response.

**Comment by nedosa** [comment] 2017-03-02 19:32
oh dear, my bad, thank you so much for your help!

**Comment by jkelvie** [comment] 2017-03-02 19:44
No problem! Glad I could help!

**Closed by jkelvie** 2017-03-02 19:44 UTC
